const Menu = [
  {
    id: 1,
    image: "IMAGES/download (1).jpg",
    name: "maggi",
    category: "breakfast",
    price: "12₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },

  {
    id: 2,
    image: "IMAGES/download (2).jpg",
    name: "allu pakoida",
    category: "evening",
    price: "20₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 3,
    image: "IMAGES/download (3).jpg",
    name: "corn",
    category: "breakfast",
    price: "10₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 4,
    image: "IMAGES/download (4).jpg",
    name: "chola",
    category: "lunch",
    price: "50₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 5,
    image: "IMAGES/download.jpg",
    name: "pizza",
    category: "evening",
    price: "80₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 6,
    image: "IMAGES/images (1).jpg",
    name: "Non-Veg Thali",
    category: "dinner",
    price: "180₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 7,
    image: "IMAGES/images (2).jpg",
    name: "Sweets",
    category: "dinner",
    price: "60₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 8,
    image: "IMAGES/images (3).jpg",
    name: "Rajma Rice",
    category: "lunch",
    price: "60₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 9,
    image: "IMAGES/images.jpg",
    name: "samaso",
    category: "evening",
    price: "10₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 10,
    image: "IMAGES/images.jpg",
    name: "timepass",
    category: "timepass",
    price: "80₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
];
export default Menu;
